@startuml

[*] --> ProfileScraping
ProfileScraping --> ImageCaptioning
ProfileScraping --> SentimentAnalysis
ProfileScraping --> LinkScraping
ImageCaptioning --> BuildCorpus
SentimentAnalysis --> CollectStatistics
LinkScraping --> BuildCorpus
BuildCorpus --> KeywordExtraction
KeywordExtraction -> BuildProfile
CollectStatistics -> BuildProfile

@enduml